### ISSUE TITLE
How to incorporate Roll-call in my own application?

### ISSUE THREAD

**Issue by ansarizafar** [mikeal/peer-call#108]
Is it possible to incorporate Roll-call in my own application? Could you please release basic functionality with an api as an npm package?

**Comment by mikeal** [comment]
been working on this in a branch, will update once it works :)

**Comment by mikeal** [comment]
branch is merged, still needs docs.

**Comment by ansarizafar** [comment]
Awasom. Waiting for Docs.

**Comment by mikeal** [comment]
Fixed and documented. https://github.com/mikeal/roll-call#embedding
