### ISSUE TITLE
Persistent settings

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#12]
We need a UI for application level settings that persists them (into localStorage is the easiest).
- Default name
- Input device
- Avatar image??

**Comment by vladaspasic** [comment]
I was thinking how we should handle User avatar images, without a remote storage. We can store the image `base64` in the local storage. Image needs to be small, preferably under 200kb. Additionally we can compress the image data before storing and decompress it when extracting. I am not sure if we can reuse JsZip for this, as at is a diff usecase, but I found this small [script](http://almostidle.com/tutorial/javascript-string-compression) that can compress a string. 

It would be great if we can display the avatars of users in the call. I can create a branch where users can upload their image, store them and show them in the audio tile.

**Comment by mikeal** [comment]
Ideally we wouldn't put it in localStorage but instead stick it in a storage mechanism that won't block the UI thread.

Something along these lines is probably best: https://hacks.mozilla.org/2012/02/storing-images-and-files-in-indexeddb/

If we can store the Blob object we can easily get an objecturl for it and use that for <img>'s without worrying about blocking any UI rendering.
