### ISSUE TITLE
Audio input source selection

### ISSUE THREAD

**Issue by Fishrock123** [mikeal/peer-call#20]
I use an external microphone, having an option of this is very helpful.

I may be willing to do this but probably will not get to it within the next two weeks at least.

**Comment by mikeal** [comment]
I had code somewhere to do this, it's not that hard, it's just an extra step.

I'd prefer to stick this in the "settings UI" which is https://github.com/mikeal/roll-call/issues/12

**Comment by mikeal** [comment]
Fixed! Check it out on the settings page :)
