### ISSUE TITLE
ability to listen in without an input device

### ISSUE THREAD

**Issue by ghost** [mikeal/peer-call#22]
My computer has problems with line in:

```
Object {name: "DevicesNotFoundError", message: "", constraint: ""}
```

It would be good if this app could gracefully disable transmit for this case. This might also be useful for bots.

**Comment by mikeal** [comment]
This is pretty easily doable, in fact it would already work for bots (they would just use the underlying swarm and connect to the room).

One thing I worry about is people trying to use this for "live shows" where many people connect and only listen. Until there is better code in the underlying swarm to proxy data and create "super nodes" the swarm won't scale very well over 10 or 20 peers. I have some code in another project that streams data to the server and presents it in an <audio> element for listen-only streams for that specific use case, but it would be cool if we could make that work fully p2p.

**Comment by chromakode** [comment]
I've whipped up a quick fix to this in https://github.com/mikeal/roll-call/pull/30
