### ISSUE TITLE
Safari doesn't have AudioContext

### ISSUE THREAD

**Issue by Haroenv** [mikeal/peer-call#23]
However it _does_ have `webkitAudioContext`, so most support could be added by adding this prefix for extra support.

**Comment by gimenete** [comment]
This can be fixed this way:

```
const AudioContext = window.AudioContext || window.webkitAudioContext
const context = new AudioContext()
```

But after that you will get a `NotSupportedError` in `getUserMedia` (at least in Safari 10).

**Comment by mikeal** [comment]
We should definitely fix this, but Safari doesn't have MediaRecorder _at all_ so recording won't work. We need a good dialog that shows people what they can/can't do based on their browser.

**Comment by vladaspasic** [comment]
With PR #47 there is warning message telling the user to use a latest version of Chrome, as everything works there.

**Comment by mikeal** [comment]
@vladaspasic I see a check for AudioContext, do we have one for MediaRecorder as well?

**Comment by vladaspasic** [comment]
Not atm, I will add a check for that as well
