### ISSUE TITLE
Automatically build bundle.js before checkin

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#33]
I have this setup locally but there are other projects, like the Node.js website, that automatically add a pre-commit hook to build the bundle.

So far I've been having to build the bundle manually after each PR. The `npm start` command is a little missleading because it makes the bundle work without actually building it for use in the tree.

**Comment by chromakode** [comment]
What do you think of setting up a CI like Travis to do the bundling and GitHub pages push? I've set this up for a few projects (e.g. https://github.com/hacktunes/hacktunes) and the experience of merging a commit -> automatically running tests and going live is pretty sweet.

**Comment by vladaspasic** [comment]
I found this module, https://github.com/kilianc/shared-git-hooks, that installs git hooks when user runs `npm install`. I think this could do the trick.

**Comment by vladaspasic** [comment]
@chromakode this is a good idea, we can ignore the `bundle.js`, or any build file for that matter, and have it only in the `gh-pages` branch.

**Comment by chromakode** [comment]
Here's how to set it up (e.g. w/ Travis):
- Add deploy script: https://github.com/hacktunes/hacktunes/blob/master/scripts/deploy.sh
- Add travis config: https://github.com/hacktunes/hacktunes/blob/master/.travis.yml
- Create a GitHub user (for privilege separation) and [generate a personal access token](https://github.com/settings/tokens/new). Set the token as  `GH_TOKEN` environment variable in Travis.

The result will be that any commit which is pushed to the master branch is tested, built, and then pushed as a commit to the gh-pages branch. I'd be happy to get this running if you're both game.

**Comment by chromakode** [comment]
An additional thought occurred to me tonight: we should have a stable master and a dev branch, both of which auto-build to the website. That way we can try things out rapidly in development separately from updating production, without worrying about breaking active users.

**Comment by mikeal** [comment]
That would require more infrastructure that we have today.

I wonder how far we could get with Cloudflare fancyness. /cc @terinjokes

**Comment by chromakode** [comment]
I'm not sure I understand -- what infrastructure is missing?

If it's all static files, could we build the staging branch to its own subdirectory and throw it in the same gh-pages branch? Or is there server-side stuff that's missing from that picture?

**Comment by mikeal** [comment]
This is the current configuration:
- Github gh-pages branch set to `master` with CNAME for rollcall.audio.
- Cloudflare sits in front providing, and forcing, TLS.

AFAIK, gh-pages can't host other branches at subdomains, would **love** that feature tho.

**Comment by chromakode** [comment]
Yeah, subdomain is tricker. Could potentially have a separate GitHub repo to accomplish that?

But I was thinking of something like https://rollcall.audio/staging/ for the short term. Would that suffice?

**Comment by mikeal** [comment]
Related https://github.com/nodejs/nodejs.org/issues/942#issuecomment-254313129

So, you can run a fork easily, all you need to do is enable `master` as the gh-pages branch and pull it up on https://username.github.io/roll-call

**Comment by mikeal** [comment]
Once we have tests we should just add git hooks.

**Comment by terinjokes** [comment]
@mikeal I'm sorry if you were hoping for my input last October. I think I did GitHub Notifications bankruptcy around then and missed this.
