### ISSUE TITLE
Way to mute all sound from the webpage

### ISSUE THREAD

**Issue by FotoVerite** [mikeal/peer-call#38]
Sometimes you need to do other things and you want to mute the sound on the page but not the entire computer/phone. What needs to be done to accomplish this?

**Comment by mikeal** [comment]
I just made this small change https://github.com/mikeal/roll-call/commit/3a3403b0859dfe42632338c9ff5b236290a70b0a

It makes all user output flow through one audio node.

Now you can mute it by doing:

``` javascript
masterSoundOutput.volume(0)
```

**Comment by FotoVerite** [comment]
is there any issue with memory leaks? Its possible someone could forget about the page and leave it for a long time. Just spit balling here. Chrome by itself usually crashes my computer so. :P

**Comment by mikeal** [comment]
We don't buffer anything that I know of into memory.

Even when the recording is on we write the recording to a File object in the browser to avoid this. Does profiling show it leaking memory?

**Comment by mikeal** [comment]
i'm interested in ideas for what we could consider the "monitor" audio.

adding another peer-like element seems extreme. i can't easily think of a way to add it and keep things simple.
