### ISSUE TITLE
Good First Fixes

### ISSUE THREAD

**Issue by thezachbruno** [mikeal/peer-call#53]
Hey guys!

I am new to the world of open source and this project seems to be the one I am narrowing my focus on. Is there any nitty gritty stuff anyone knows needs to be done but just has not got around to it? I would like to help out in any way I can. Though, my JS knowledge is limited, but I hope to learn as much as possible by traversing through this projects source code.

**Comment by mikeal** [comment]
Adding this issue https://github.com/mikeal/roll-call/issues/57 and the `first-timers-only` tag as recommended here https://medium.com/@kentcdodds/first-timers-only-78281ea47455#.bpckoyct0

**Comment by suamorales** [comment]
would love a few good first fixes, or simpler features for first timers :)

**Comment by mikeal** [comment]
Yup, we're using this label to call them out :) https://github.com/mikeal/roll-call/labels/first-timers-only
