### ISSUE TITLE
Default gain for remote callers to 0.10 or 0.20

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#57]
The default gain for remote callers you are listening to is too high, it should definitely come down.

This should not apply to the person's _own_ mic, only the remote callers.

The volume slider and the underlying waudio setting need to both default to this.

**Comment by thezachbruno** [comment]
I will gladly tinker with this fix. Though, I am unsure which file to refer to for the default gain.

**Comment by mikeal** [comment]
Gain nodes default to 1.0 so you'll need to do an `audio.volume()` call here:

https://github.com/mikeal/roll-call/blob/master/index.js#L335

You'll also want to adjust the slider UI default, can probably just use jQuery for that.

**Comment by janga1997** [comment]
@mikeal Is this issue still open?

**Comment by mikeal** [comment]
I don't think the audio.volume call works anymore because waudio was refactored, but we should default to 0.1 instead of 1.0.

**Comment by mikeal** [comment]
Oh, sorry, to be clear, we should default to that only for remote callers, not for *your* outbound audio.

**Comment by janga1997** [comment]
@mikeal Sorry for the trouble, but the code is a bit too complex for me to dive into completely. any hints?

**Comment by mikeal** [comment]
Ya, it's been slowly turning into more and more of a mess.

The good news is that the last few modules I did for projects similar to `roll-call` have been much cleaner because of some big changes I made to `funky`. I'm going to refactor Roll Call this month and it should be a lot easier to reason about :)

**Comment by browniebroke** [comment]
Trying to help this very cool product, but I realised the code has moved a bit since the previous comments. 
Am I right in assuming the `audio.volume` should be added somewhere around [here](https://github.com/mikeal/roll-call/blob/d9ee66befa7a99ccfdfc79bcb4bd9dcd62460f8d/index.js#L348-L357)?

(Added the changeset to the link so that it points at the same lines in 6 months)

**Comment by mikeal** [comment]
This is actually fixed in the `refactor` branch already.

**Comment by mikeal** [comment]
Closing until we get more testing in the new branch.
