### ISSUE TITLE
File sharing

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#59]
The underlying code is already there to easily share arbitrary files with everyone we just need to figure out what the UX should be around exposing newly shared files and downloading them.

**Comment by htirma** [comment]
Yeah, this would make it a lot better 😃

**Comment by mikeal** [comment]
This is implemented in the new version :)

Drag and drop in the call sends to everyone. Drag and drop into a peer's cell sends the file to just them. New GIF in the README is a screencast of it.
