### ISSUE TITLE
Drag-and-Drop audio files to play over your own channel.

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#6]
Users should be able to drop audio files into the call.

Once the element is there for a player it should play in the users' monitor as well and play into their output audio to everyone on the call.

**Comment by chromakode** [comment]
Can this be closed as of https://github.com/mikeal/roll-call/commit/22b7e30d259691b56e99b7b52d1a7d04fa62f78b?

**Comment by mikeal** [comment]
Yup :)
