### ISSUE TITLE
Mobile apps/support

### ISSUE THREAD

**Issue by htirma** [mikeal/peer-call#61]
I get it's a bit too early to think about this, but I hope its sure on the roadmap 💯

**Comment by mikeal** [comment]
I wonder how close Chrome on Android is to having everything we need to support this already?

**Comment by UziTech** [comment]
I have used this on chrome on android and it works great

**Comment by mikeal** [comment]
Oh wow, we already work on mobile!!!

**Comment by davidli2017** [comment]
cool , that is great

**Comment by htirma** [comment]
what about iOS :(

**Comment by UziTech** [comment]
unfortunately iOS only allows safari's javascript engine, even in chrome on iOS, so until safari supports [webRTC](http://caniuse.com/#feat=rtcpeerconnection) this won't work on iOS

**Comment by mikeal** [comment]
On iOS we could use Bowser http://www.openwebrtc.org/bowser

We could use it to build an installable app that would work. Probably something we want to factor in with how we build out the desktop client on Electron.

**Comment by htirma** [comment]
@mikeal that sounds pretty awesome :D

**Comment by mikeal** [comment]
Sounds like WebRTC is landing in a few months. Will look at this again once it's there.
