### ISSUE TITLE
Buttons are placed incorrectly now.

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#62]
When did this happen?

<img width="400" alt="screen shot 2016-10-17 at 4 35 40 pm" src="https://cloud.githubusercontent.com/assets/579/19459457/eb3e9bd6-9487-11e6-8146-d86b03819913.png">

**Comment by mikeal** [comment]
Pretty sure this is because the bundle didn't get updated.

**Comment by mikeal** [comment]
Yup, that was it. Fixed now. We _really_ need to get that pre-commit automation in :(

**Comment by FotoVerite** [comment]
Can you go into any detail how to accomplish pre flight. Happy to put that in.

**Comment by mikeal** [comment]
Issue is logged here https://github.com/mikeal/roll-call/issues/33

**Comment by mikeal** [comment]
Oh, also, the build process is just `browserify index.js > bundle.js`
