### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dulichan** [mikeal/peer-call#64]
Hi guys,
Is this based on MIT license? Can someone reuse the audio recording tech you guys are using? 

Cheers~

**Comment by mikeal** [comment]
> Is this based on MIT license? 

Nope, Apache 2.0 https://github.com/mikeal/roll-call/blob/master/package.json#L16

> Can someone reuse the audio recording tech you guys are using?

Yes, absolutely, Apache-2 is just as permissive as MIT :)
