### ISSUE TITLE
Operation is not supported error when about to record audio

### ISSUE THREAD

**Issue by vladaspasic** [mikeal/peer-call#66]
On my version of Mozilla browser, I get an error when trying to record a conversation. After a bit of digging, I found out that the problem is in the `mimeType` property we pass to the `MediaRecorder`, as `audio/webm;codecs=opus` is not supported by my browser.

We should maybe have a list of fallback types, that we support, and check if they are supported by using the `MediaRecorder.isTypeSupported` method. In my browser case, it has has support for `audio/ogg`.

**Comment by mikeal** [comment]
Good idea.

We'll also need to alter some of the file naming code to stop assuming .webm.

**Comment by vladaspasic** [comment]
OK, I will pick up this one, as I can easily replicate it.

**Comment by mikeal** [comment]
We should probably put these into a preferred order. The ogg container is more widely recognized by audio editing programs than .webm so I'd definitely prefer that one.

**Comment by mikeal** [comment]
New version requires Chrome because of WebComponents support.
