### ISSUE TITLE
Separate code concerns and add tests

### ISSUE THREAD

**Issue by MarcL** [mikeal/peer-call#68]
Are you planning on fleshing out the app code structure a bit more? I'd like to see some separation of the UI and recording code into different modules from `index.js`. I appreciate it's early days but just thought it was probably worth doing early while the codebase is small.

Any thoughts on adding tests too? Feels weird raising a PR without any corresponding test code! 😄

**Comment by bmathews** [comment]
See #41 and #55

**Comment by MarcL** [comment]
Great stuff. Sorry, didn't see those issues so I'll close this one. 👍
