### ISSUE TITLE
Use webworker to create a ZIP file

### ISSUE THREAD

**Issue by vladaspasic** [mikeal/peer-call#72]
Maybe it would be a good idea to generate the ZIP file on a separate thread, using WebWorkers, so it wont effect our UI performance in the browser.

We could never know how big this audio file could get, imagine if we record a conversation for an hour, or more, and try to zip it on the UI thread.

This also raises couple of questions, what is the file size limit, is there a limit, should we split the big file in chunks, and store them somewhere (IndexDB), and zip these chunks later in a folder?

**Comment by vladaspasic** [comment]
Just tried it out locally, it was working fine when compressing the files with a webworker. I will create a pull request if you wanna check it out.

**Comment by mikeal** [comment]
If we can stick the loading on the zipjs code into the worker we could actually kick off this as soon as the recording is stopped so that it's ready by the time someone goes to download it :)

**Comment by mikeal** [comment]
Moved to an async API for this which is much faster. Not sure it's worth putting in a worker anymore.
