### ISSUE TITLE
Expose "hidden" features.

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#77]
We have a variety of hidden features that need to be exposed explicitly or be made more discoverable.
### Customized room names

You can use any string as a room name. This makes the urls nicer and more human readable. Additionally, if you are recording the call the name of the .zip file is set to the name of the room.
### Recording delay is encoded into the file names.

The individual tracks produced by recording have the time in milliseconds they are delayed from the beginning of the recording. This is useful if a connection is slow or if someone connects into the call late.
### Drag and drop files into the call.

Right now if you drop audio files into the call you can play them into the call.

A future version will also integrate file sharing as well.

**Comment by htirma** [comment]
woot! sound cool...

**Comment by mikeal** [comment]
faq.html is in the tree. still needs docs for the new file sharing feature and recording tho.
