### ISSUE TITLE
Move to webpack

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#78]
The way that we are using browserify and beefy seems like a case that webpack would be pretty good at. It could definitely speed up development mode, builds are starting to take a little too long.

**Comment by ghost** [comment]
This app uses packages with heavy node idioms with Buffer, process.nextTick, streams, loading json files and some implicit transforms for example hyperlog and protocol-buffers both use brfs. That seems pretty daunting to get webpack to work with.

I could make rebundling faster in browserify core instead. There are many optimizations in the rebuild pipeline that I haven't gotten around to implementing.

**Comment by ghost** [comment]
This might be a better flow for your build script in the mean time:

```
"start": "budo index.js:bundle.js"
```

budo waits for the code to finish compiling before serving the bundle.js so you don't have to refresh a bunch of times.

**Comment by mikeal** [comment]
Been using budo in another projects for the last few days and it seems to fix this problem. I'll move roll-call to it in the branch I'm in.

**Comment by mikeal** [comment]
Moved to budo, it's all good.
