### ISSUE TITLE
Muting another user actually mutes your audio

### ISSUE THREAD

**Issue by MarcL** [mikeal/peer-call#81]
I just spotted a bug when looking at the mute all issue (https://github.com/mikeal/roll-call/issues/38) and noticed that you can click another users's mute button and it mutes your own.

We should probably ghost (or remove?) other users mute icons and not allow them to be clickable. Perhaps better to just ghost them if the plan is to show whether remote users are muted or not.

**Comment by mikeal** [comment]
I fixed this in the web components branch but haven't in master yet.

**Comment by MarcL** [comment]
Ok thanks @mikeal. Do you think it might be worth waiting until you've merged the web components branch until picking up anything else then? Looks like it's an architectural change so feels like it's best to hold off for now.

**Comment by mikeal** [comment]
I'm actually going to close the other branch. It's  a little too experimental to land. Let's just get this fixed on master.

**Comment by mikeal** [comment]
Fixed in new version.
