### ISSUE TITLE
Zip download is broken

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#87]
Tested on Chrome and Brave.

When you stop recording it just spins forever.

**Comment by mikeal** [comment]
@vladaspasic any idea what might have broken here?

**Comment by vladaspasic** [comment]
This request returns a 404 https://rollcall.audio/worker.js

**Comment by mikeal** [comment]
@chromakode looks like this didn't make it over in the new build stuff.

**Comment by vladaspasic** [comment]
I guess we need to add `worker.js` to this list in the `deploy.sh` script https://github.com/mikeal/roll-call/blob/master/scripts/deploy.sh#L21

**Comment by vladaspasic** [comment]
I think we can close this one, as the file is now accessible.
