### ISSUE TITLE
Move asset copying out of deploy.sh

### ISSUE THREAD

**Issue by chromakode** [mikeal/peer-call#89]
The assets to copy in `deploy.sh` may vary between commits, and differ between `stable` and `master` branches. We should move the copy_assets functionality in to another file so that it gets checked out when `deploy.sh` moves between branches. I think `npm run copy_assets` would be a good way to do it.

**Comment by mikeal** [comment]
I think we may need to just remove the staging/master system.

Currently, we are re-deploying both on every commit and, to fix another bug, I ended up having to npm install for each branch which drastically increases the build time :(
