### ISSUE TITLE
Add visual instructions

### ISSUE THREAD

**Issue by mikeal** [mikeal/peer-call#9]
It's not entirely obvious that what you should be doing in order to share the current room and have others call in is to copy/paste the url around.

Optionally, we could also have a "share" button.

**Comment by htirma** [comment]
Is this gonna be the onboarding?

**Comment by mikeal** [comment]
we have the share button now but we still don't have any text on the front page explaining what Roll Call is.

**Comment by MarcL** [comment]
@mikeal - Hello! As I said on Twitter, I'd like to get involved with the project and although I've been a developer for 20+ years, I've never really really contributed to open source projects except for the odd bug fix. This feels like something I can pick up just to find my way around the project and learn a bit more about semantic-ui.

Is there any particular copy or styles that you want on the front page?

Thanks,
Marc

**Comment by mikeal** [comment]
We should talk about what Roll Call is and maybe walk through a few features. This can all go below the current "join party / create room" buttons.

**Comment by MarcL** [comment]
Ok cool. Let me have a look and then I'll PR. Thanks.

**Comment by thezachbruno** [comment]
Was anyone thinking of just using Bootstrap Tour? It appears quite easy to implement and I personally believe it would make for a great "up and running" feel for the user when they first enter. Maybe have the first popup ask the user to choose a room, then prompt them to invite a new user to talk to them. After the user is invited then show them how to add audio and do some other cool functions.

**Comment by MarcL** [comment]
@chemeyo - Yes, I did think that something similar would be good but my assumption was that this issue was going to be an MVP to get some info on the screen. After that we could add a tour using Bootstrap Tour / Shepherd (or similar).
