### ISSUE TITLE
Settings modal is not contained to modal; user will see modal spill out of modal.  

### ISSUE THREAD

**Issue by suamorales** [mikeal/peer-call#91]
When a user clicks the settings icon the user will see a modal pop up. This modal has extra white space on the right which should not be visible. 
OSx 10.10 
Chrome 54

<img width="1065" alt="screen shot 2016-10-28 at 8 08 40 pm" src="https://cloud.githubusercontent.com/assets/9709819/19825691/7451e7e6-9d4a-11e6-9afd-a1389af208de.png">

**Comment by mikeal** [comment]
@vladaspasic does this happen to be fixed with the avatar update? I know the layout changes a bit with that.

**Comment by suamorales** [comment]
my PR: https://github.com/mikeal/roll-call/pull/92

**Comment by mikeal** [comment]
No more modals in the new version :)
