### ISSUE TITLE
Unable to change audio input

### ISSUE THREAD

**Issue by bfbraum** [mikeal/peer-call#93]
Four of us started a recorded call. The others told me that my audio sounded like it came from my laptop input (Macbook Air, 13-inch, late 2010). I changed the selected input to headphone (Microsoft Lifechat LX-3000) and double-checked that the system audio was the same, but the input continued to come from the laptop.

**Comment by mikeal** [comment]
Perhaps this doesn't work yet without a restart. I think we implemented this setting before we have actually abstracted the outbound audio enough to dynamically switch them, should be able to do it now though.

**Comment by mikeal** [comment]
Removed this feature for the web, the UI for it complicates the experience way too much.

Once we build a desktop client it'll have this built-in and can be MUCH more reliable since you don't have to request permissions to access the devices.
