### ISSUE TITLE
The stable branch site ain't working

### ISSUE THREAD

**Issue by karuppiah7890** [mikeal/peer-call#96]
Hey @mikeal 

There are some issues with loading the js and css files within the vendor folder. I have no idea why. Something creepy.

But the site at staging branch (staging folder in gh-pages branch) works perfectly. It's just strange. 

https://github.com/mikeal/roll-call/tree/gh-pages

I tried looking into it. But the URL for the js and css files look fine to me. I have no idea why the URLs give an error. But https://rollcall.audio/staging page doesn't give any similar errors, though they have similar code and similar URLs to load the js and css resources from the vendor folder.

![rollcall](https://cloud.githubusercontent.com/assets/12808424/20601677/d5b6818c-b27f-11e6-8e34-328d92c2999d.png)

**Comment by mikeal** [comment]
@chromakode any idea what this might be?

**Comment by mikeal** [comment]
I'm pretty sure I fixed this about a week ago :)

**Comment by karuppiah7890** [comment]
Yeah, I noticed. But how did you fix it ? I guess it was just a redeployment and it got weirdly fixed, is it so ?

**Comment by mikeal** [comment]
There was a bunch of work pending in master that got merged and one of the changes fixed it, which isn't too surprising because /staging was working the whole time.
