### ISSUE TITLE
Kick people out from a call

### ISSUE THREAD

**Issue by mario-lemes** [mikeal/peer-call#98]
Hey @mikeal,

First of all, congratulations for all this awesome project, you have done a really good job (also in signal-exchange, room-exchange and of course killa-beez).

I have been playing around with all those packages because I found them pretty interesting but is harder to understand in deeper what the code does. I'm doing it little by little. It would be awesome if you can recomend some documentation in each of those projects I mention to get a deeper knowledge of the workflow.

Beside of all that, I have a question: Is there any way to kick people out from a room? I tried triggering this peace of code when the user for example click on a button placed beside the user name.

`swarm.sendSignal(publicKey, 'disconnect')`

But it didn't work. 

Any help would be really appreciated, thank you!

**Comment by mikeal** [comment]
There's no code *yet* to disconnect from someone. Allowing a single person to disconnect from a peer is pretty simple but it's also not that useful for a few reasons:

1. They will still be connected to the other peers in the call.
2. They could refresh the page and reconnect pretty quickly. The publicKey for that peer will be re-generated and there isn't a permanent token yet that identifies that user.

There's a few things that I'll be building eventually that can solve this:

1. Private calls (identified by the publicKey of the moderator). This would give a person administrative rights over the call the other peers will respect.
2. Authenticated peers using signing chains. Essentially this is a service that sends an email to a user and then signs a key they have stored locally which they then include in their signing chain. This gives a permanent user id even tho the connection keys are temporary. It would be easy to then lock calls to authenticated users and have white lists and block lists.

**Comment by mario-lemes** [comment]
Hey @mikeal,

So, how is this listener triggered?
```
this.swarm.on('disconnect', function (publicKey) {
...
});
```

And, even is not useful at all, how would be possible to disconnect yourself from a call without refreshing?

Thanks

**Comment by mikeal** [comment]
That happens when a peer disconnects, either because of a network failure or because they close the tab. It's useful because you need to remove callers from the UI that have disconnected.

**Comment by mikeal** [comment]
The swarm is built on top of `simple-peer`. https://github.com/feross/simple-peer

It looks like `peer.destroy()` is the function you're looking for :)

**Comment by mario-lemes** [comment]
Cool @mikeal,

I will try that and see how it works.

Thank you!

**Comment by mikeal** [comment]
Anytime ;)
